

<div class="clearfix"> &nbsp; </div>
<div class="container">

    <div ng-controller="">

        <h3>Hello { php-cache } with zend framework 3, time = <?php echo $this->ttl;?> sec.  </h3>

		<hr/>

		<ul>
			<li><p>array [3, 5, 9, 15, X] :: <span class="<?php echo $this->fooColor;?>"> <?php echo $this->foo;?> </span></p></li>
			<li><p>array (X + (2^4)) + (10 * 2) = 99 :: <span class=" <?php echo $this->barColor;?>"> <?php echo $this->bar;?><span></p></li>
		</ul>
	

		<hr/>
		<p><a class="btn btn-primary" href="#" onclick="window.location.reload()""  role="button">Refresh</a></p>
	</div>
</div>